### PR TITLE
Merge changes for v0.2.0

### PR DESCRIPTION
**Pull request by Benjozork**
- Fixed/Added javadocs for some classes

### CODE REVIEW

**Comment by Benjozork** [comment]
DO NOT merge before v0.2.0 is completed

**Comment by Benjozork** [comment]
v0.2.0 is complete, awaiting confirmation by @angelickite or @sozemego to merge into master.

**Comment by angelickite** [comment]
Theres a few things i consider questionable. Like for example the way the screen setting works or how multiple glyphlayouts are generated even though they are heavy objects among other things.

Though these issues can be addressed later through individual issue tickets. Blocking master branch any longer seems like the worst option so im ok with this for now.

**Comment by Benjozork** [comment]
@angelickite good points. I'll merge when you accept the review.

**Review by angelickite — APPROVED** [review]

**Pull request merged**
